### ISSUE TITLE
Assigning black fill + outline prevents body style formatting

### ISSUE THREAD

**Issue by jpecor** [adafruit/Adafruit_CircuitPython_Display_Button#10]
The ```if outline_color or fill color:``` check fails when both _fill_color_ and _outline_color_ are set to **_0x000000_**. As a result, the body style formatting is never applied, and the button is not added to the display group.

**Comment by ladyada** [comment]
@jpecor see if you can fix it, try changing the if to
`if (outline_color is not None) or (fill_color is not None)` instead!

**Comment by jpecor** [comment]
Yes, that will work.

Is it the intent to allow "transparent" buttons by setting the outline/fill to None, then?  It's a nifty feature that I didn't really even realize was possible until I was doing some testing with this issue.

I can submit a PR with your recommended fix.  That works.

**Comment by ladyada** [comment]
yes thats right, it allows transparancy, a PR would be great :)

**Comment by jpecor** [comment]
Ok, great.  Thanks!

**Comment by jpecor** [comment]
Thanks ladyada!

**Comment by makermelissa** [comment]
Fixed via #11
