### ISSUE TITLE
Button has a Group, but is not a subclass of Group

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_Display_Button#12]
JMK expected a `Button` to act like a `Label`, in that it would be a `Group` that you would add to a `Group`. But `Button` is not a subclass of `Group`: It has a `Group` (`.group`), but it is not itself one.

There is a mirrored page in Learn Guides with an example that assumes a `Button` is a `Group`:
https://learn.adafruit.com/pyportal-calculator-using-the-displayio-ui-elements/ui-quickstart#button-3-15
https://learn.adafruit.com/circuitpython-display-support-using-displayio/ui-quickstart

Is it possible for it to be `Group`? If not, the examples should be fixed, and  the documentation here should explain how to use `.group`.

Tagging @makermelissa @tannewt @ladyada

**Comment by ladyada** [comment]
i vaguely recall there was a reason i had to do it this way, like it wasnt working to make it a group subclass, but im almost sure its been fixed now.
@makermelissa wanna try makin' it a group? it will either Totally Work or you'll bump into the thing i did.

**Comment by makermelissa** [comment]
Sure, I can give it a try.

**Comment by tannewt** [comment]
Yup, it used to not work but now it should.
