### ISSUE TITLE
Please remove the custom font usage or add note

### ISSUE THREAD

**Issue by RichardA1** [adafruit/Adafruit_CircuitPython_Display_Button#14]
It was very confusing to have to deal with the custom font usage for the display_button_simpletest.py example.

Please add a note to line 22 letting people know that they need to add the font file to a directory named fonts on CIRCUITPY. I would also suggest that you just remove the custom font and use the terminalio.FONT to bring the focus back to simple button use. Maybe put the custom font option in comments.

Thanks :)

**Comment by ladyada** [comment]
hi you can submit a PR and we'll take a look

**Comment by makermelissa** [comment]
Before removing the font altogether, please note that some projects currently use this such as https://learn.adafruit.com/pyportal-calculator-using-the-displayio-ui-elements/initial-setup

**Comment by makermelissa** [comment]
My suggestion would be to add some more buttons to the simpletest that just use terminalio.FONT so users can see additional usage without the custom fonts.

**Comment by caternuson** [comment]
@makermelissa I'm not seeing how changing `display_button_simpletest.py` here would affect the calculator code? Maybe I'm missing something.

Could we make `display_button_simpletest.py` just use `terminalio.FONT`. And then we can add another demo, like `display_button_font.py` or something to show use of custom fonts.

**Comment by makermelissa** [comment]
Ah, I may have misread that when I posted. That sounds good to me.

**Comment by caternuson** [comment]
Should be fixed with #16 and released as 1.2.1
https://github.com/adafruit/Adafruit_CircuitPython_Display_Button/releases/tag/1.2.1
