### ISSUE TITLE
FR: Image button

### ISSUE THREAD

**Issue by KTibow** [adafruit/Adafruit_CircuitPython_Display_Button#28]
It would be nice to have a way to make an image button, instead of having to use a label.

**Comment by kmatch98** [comment]
There’s a new `icon_widget` in the displayio_layout library:
https://github.com/adafruit/Adafruit_CircuitPython_DisplayIO_Layout/pull/12

Here is a link to the docs page:
https://circuitpython.readthedocs.io/projects/displayio-layout/en/latest/api.html#icon-widget

**Comment by ladyada** [comment]
closin since its probably resolved now!

**Comment by KTibow** [comment]
Nice! Thanks!
