### ISSUE TITLE
`name` argument in constructor seems unused

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_CircuitPython_Display_Button#35]
The Button constructor takes an argument called `name` and sets it into a variable on self, but it appears to be unused beyond getting put into that variable. 

I think it could be removed. We can do a scan on learn guide and examples to ensure nothing has attempted to use it before doing so though.

**Comment by CedarGroveStudios** [comment]
`name` is used in the soundboard example. Don't know about use in learning guides.

I've found it very handy for uniquely identifying a button independent of its label. Especially useful when dealing with a large number of on-screen buttons as in my HP-35 calculator project with 35 small buttons on a PyPortal Titano with limited available label space.

**Comment by FoamyGuy** [comment]
That is good enough for me. Definitely worth keeping if there is code out there using it, and it's helpful.
