### ISSUE TITLE
Add a label orientation flag to Button 

### ISSUE THREAD

**Issue by n0mn0m** [adafruit/Adafruit_CircuitPython_Display_Button#9]
`Button` allows you to position an instance horizontally or vertically based on the `x`,`y` co-ordinates it's created with. Labels default to a horizontal layout though. I'm wondering if labels should support a similar `x`,`y` system in the bounding box of the `Button` instance it belongs to, or something like an `orientation`/`rotation` flag? 

Happy to help contribute to adding this functionality, but wanted to get some feedback first.

**Comment by kattni** [comment]
@n0mn0m Apologies for the delayed response. Please let me know if this is still something you're interested in and we can discuss it further. Thanks!

**Comment by n0mn0m** [comment]
@kattni no problem. I'm definitely up to add this flag/feature. The PyPortal I have is occupied. Let me look at getting a hold of another. Happy to go ahead and discuss/begin implementing this until I have another board to load/validate the functionality on.

**Comment by kattni** [comment]
@n0mn0m Please put together some code to show what you have in mind. Follow the API already present in the library. You can put in a PR that is a WIP if you'd like, as it makes discussion and so on easier. For our suggested Git/GitHub workflow, please check out [this guide](https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github). Ping me if you have any questions.

**Comment by kmatch98** [comment]
This will benefit from the feature developed for display_text here: https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/pull/122

**Comment by jposada202020** [comment]
I think this is developed in:
DisplayIO_button https://github.com/adafruit/Adafruit_CircuitPython_Display_Button/blob/master/adafruit_button.py
and as mentioned by @kmatch98  in the new feature in label that allows text to be display in different directions. These changes were introduced in 2.17 for Label and 2.18 for Bitmap_label.
